### ISSUE TITLE
Load options from $HOME instead

### ISSUE THREAD

**Issue by binarykitchen** [victorporof/Sublime-JSHint#103]
When I delete the options at `~/.config/sublime-text-3/Packages/JSHint Gutter/.jshintrc`, and attempt to set the linting preferences of this plugin via Sublime's menu, it does generate a new `.jshintrc` file.

But I want the plugin to read the `.jshintrc` file in my $HOME folder instead. How can I configure that? Or is this a feature? Not sure here ...

**Comment by victorporof** [comment]
Instead of deleting the .jshintrc, replace the contents with {}, so there won't be any default options.

**Comment by binarykitchen** [comment]
Ok, contents in `~/.config/sublime-text-3/Packages/JSHint Gutter/.jshintrc` are `{}` now. So, when I place my global `.jshintrc` in my $HOME folder, it should parse them, shouldn’t it?
