### ISSUE TITLE
ValueError: Error from jshint: util.puts: Use console.log instead

### ISSUE THREAD

**Issue by DeviaVir** [victorporof/Sublime-JSHint#104]
Not a major issue since it won't impact a lot of people. 

When running `io.js` (v1.2.0) instead of node, JSHint stops working in Sublime Text. The console shows the following stack:

```
Writing file nodejs/lib/api.js with encoding UTF-8
Starting tests in nodejs
Traceback (most recent call last):
  File "./SublimeLinter.py", line 431, in _update_view
  File "./SublimeLinter.py", line 143, in run_once
  File "./sublimelinter/modules/base_linter.py", line 291, in run
  File "./sublimelinter/modules/javascript.py", line 72, in parse_errors
ValueError: Error from jshint: util.puts: Use console.log instead
[]
```

If there is an error in my file the `[]` would show it still, so it's not like I can't still check.

**Comment by DeviaVir** [comment]
Apparently this had nothing to do with it after all, was just my Sublime Text. Sorry for any caused confusion!

**Comment by tysonzero** [comment]
Would you care to explain what you did to fix that issue with your Sublime Text? I'm having the same problem; any help would be greatly appreciated.

**Comment by DeviaVir** [comment]
@tysonzero I removed a whole bunch of packages and then installed `JSHint Gutter`. That worked fine for me.

**Comment by tysonzero** [comment]
Thank you! I installed `JSHint Gutter` and put `"javascript_linter": "",` in my sublime-settings and it worked great.

**Comment by craiglondon** [comment]
Thanks for the bug submission,  I'll have to try this on my own install to see if that fixes the same issue I had.
