### ISSUE TITLE
Lint on save – where can I see the messages?

### ISSUE THREAD

**Issue by nilssolanki** [victorporof/Sublime-JSHint#106]
When I select the lint on save option (which is awesome), I can't seem to find the error messages. I only see the orange triangles in the gutter. Would it be possible to show the error message when I either:

1. Hover over the triangle
2. Move to the line with the error

Or is there another possibility that I'm not aware of?

**Comment by victorporof** [comment]
If you click on the underlined text, the error is displayed in the editor's footer.
