### ISSUE TITLE
Only able to see errors when JSHint > Lint Code

### ISSUE THREAD

**Issue by gin93r** [victorporof/Sublime-JSHint#108]
ST2

I don't seem to have any icons in the gutter. Lint on load/save doesn't appear to do anything. Highlight selected regions doesn't appear to do anything either.

If I run JSHint > Lint Code via the menu or the key command, I will get the errors listed at the bottom of the editor.

Is there a setting I'm missing, or something else?

I have node, jshint installed.

**Comment by victorporof** [comment]
Same underlying issue as https://github.com/victorporof/Sublime-JSHint/issues/94
