### ISSUE TITLE
invalid "use strict" error when using a self executing function

### ISSUE THREAD

**Issue by salientgreen** [victorporof/Sublime-JSHint#117]
When linting a self executing function, the error 'Missing "use strict" statement.' is displayed even though strict mode is declared within the function. This can be replicated on LInux (Mint 17.2), Sublime Text 3 (build 3083), and JSHint Gutter (v2015.03.18.14.31.56) here with the following code.

    /* exported test */

    var test = (function(){
        "use strict";
    })();

**Comment by victorporof** [comment]
If you feel like jshint isn't properly respecting the options passed in, please file this bug at https://github.com/jshint/jshint
