### ISSUE TITLE
quotmark has been deprecated

### ISSUE THREAD

**Issue by yanyu0517** [victorporof/Sublime-JSHint#122]
The quotmark option has benn deprecated[http://jshint.com/docs/options/#quotmark](http://jshint.com/docs/options/#quotmark "quotmark"),and the last version jshint have set default to false.

It is better removed or set to false.

**Comment by victorporof** [comment]
Removed. https://github.com/victorporof/Sublime-JSHint/commit/9bb651adc49a81721adc027daf49db90adf30605
