### ISSUE TITLE
Bad option: "esversion"

### ISSUE THREAD

**Issue by evolutionxbox** [victorporof/Sublime-JSHint#123]
Whilst writing my lovely code, I find that my code fails tests!
**"This cannot stand!"**, I cried.

In the gutter, a curious warning triangle can be seen:
<img width="301" alt="screen shot 2016-01-16 at 23 09 29" src="https://cloud.githubusercontent.com/assets/660368/12375002/6464ea20-bca6-11e5-90dd-e1755e165a9c.png">
Accompanied by some more nefarious text in the footer:
<img width="385" alt="screen shot 2016-01-16 at 23 09 51" src="https://cloud.githubusercontent.com/assets/660368/12375001/6464d80a-bca6-11e5-879b-931f3e027ebb.png">

Does there exist such a person of whom can help me with my predicament?

---
#### Options

`.jshintrc` (project root)
```JSON
{
  "esversion": 6,
  "devel": true,
  "browser": true
}
```

`.jshintrc` (JS Hint Gutter)
```JSON
  "browser": true,
  "esnext": true,
  "globals": {},
  "globalstrict": true,
  "quotmark": true,
  "undef": true,
  "unused": true,
  "devel": true
}
```

**Comment by victorporof** [comment]
Take "esversion" out of your .jshintrc (project root).

**Comment by evolutionxbox** [comment]
If I do that, I am left with a plethora of ES6 related errors when I run `npm run test` (jshint command line).

Surely `esversion` is a valid jshint option?

**Comment by victorporof** [comment]
Hmm, it would seem that error is generated by jshint itself. Have you tried `npm update` inside the scripts folder to update to the latest version?

**Comment by evolutionxbox** [comment]
Hmmm, my jshint is on version `2.9.1`...

**Comment by victorporof** [comment]
Can you get `jshint` to generate the exact same error when used outside this plugin? If so, please file a bug there.

**Comment by evolutionxbox** [comment]
I'll try that tonight. If you hear nothing, it's likely I've forgotten...
Thanks, @victorporof

**Comment by evolutionxbox** [comment]
I get the following error when I remove the `esversion` from `.jshintrc`:
```bash
src/index.js: line 3, col 1, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
src/index.js: line 6, col 3, 'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
src/index.js: line 8, col 3, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
src/index.js: line 12, col 3, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
src/index.js: line 16, col 3, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
src/index.js: line 17, col 3, 'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
```
