### ISSUE TITLE
Sublime-JSHint gives different errors from shell-invoked jshint (same version 2.9.1)

### ISSUE THREAD

**Issue by cleverplatypus** [victorporof/Sublime-JSHint#126]
Sublime-JSHint doesn't give the same outcome as the globally installed jshint executable.

In particular, some syntax errors are overlooked and I get an error for some directives like **// jshint ignore: line** 

> Incompatible values for the 'undefined' of 'undefined' linting options

The versions seem to match, 
```
$ which jshint
/usr/local/bin/jshint

$ jshint -v
jshint v2.9.1

$ node -v
v0.10.35

$ grep version JSHint\ Gutter/scripts/node_modules/jshint/package.json
"type": "version"
"version": "2.9.1"
```

Any particular reason?
Cheers

**Comment by victorporof** [comment]
There is a default set of settings added by the plugin. See .jshintrc file bundled, or right click -> jshint -> edit plugin settings.

**Comment by mmeisel** [comment]
I think this should be reopened, I'm also seeing the error "Incompatible values for the 'undefined' of 'undefined' linting options", which isn't present at the command line, for the jshint comment at the top of my file. In my case, it's:
```
/*jshint node:true */
```

**Comment by hc-12** [comment]
@mmeisel as mentioned. I too also see the following error:

> Incompatible values for the 'undefined' of 'undefined' linting options

I've changed `run.js` from line 197 to:
``` javascript
      if (e.raw) {
        // var message = e.raw
        //   .replace("{a}", e.a)
        //   .replace("{b}", e.b)
        //   .replace("{c}", e.c)
        //   .replace("{d}", e.d);
          var message = e.reason;
```

Which gives me the real error:
`Incompatible values for the 'esversion' of 'esnext' linting options`

As it turns out you cannot use:
`esversion: 6`

with 

`esnext: true`

**Comment by joshguptill** [comment]
I had the same problem, but I closed and restarted sublime (after commenting out the built in jshintrc rules) and that error went away.

**Comment by huexotzinca** [comment]
I had the same problem; and like say @hc-12 you must be check your .jshinrc file in your project or file directory and the Packages/JSHint Gutter/.jshintrc ( you can access to this file through Rigth click > JSHint > Set Linting Preferences  ) for incompatibility.
