### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'NaN'

### ISSUE THREAD

**Issue by xeroxoid** [victorporof/Sublime-JSHint#128]
Hi, first of all thanks for this awesome package!

Now I'm not seeing any errrors for ```camelcase: true``` and initially I thought that the ```.jshintrc``` file used was not the correct one (in my client directory). The I set ```"print_diagnostics": true``` in the JSHint settings file and saw that the linting options are correct, i.e.: 

```javascript
Using JSHint options: {
  "browser": true,
  "esnext": false,
  "strict": false,
  "undef": true,
  "unused": false,
  "bitwise": true,
  "camelcase": true,
  "curly": true,
  "eqeqeq": true,
  "es3": false,
  "forin": true,
  "freeze": true,
  "immed": true,
  "indent": 2,
  "latedef": "nofunc",
  "newcap": true,
  "noarg": true,
  "noempty": true,
  "nonbsp": true,
  "nonew": true,
  "plusplus": false,
  "quotmark": "single",
  "maxparams": 10,
  "maxdepth": 5,
  "maxstatements": 40,
  "maxcomplexity": 8,
  "maxlen": 120,
  "asi": false,
  "boss": false,
  "debug": false,
  "eqnull": true,
  "evil": false,
  "expr": false,
  "funcscope": false,
  "globalstrict": false,
  "iterator": false,
  "lastsemic": false,
  "laxbreak": false,
  "laxcomma": false,
  "loopfunc": true,
  "maxerr": false,
  "moz": false,
  "multistr": false,
  "notypeof": false,
  "proto": false,
  "scripturl": false,
  "shadow": false,
  "sub": true,
  "supernew": false,
  "validthis": false,
  "noyield": false,
  "node": true
}
```

I am also getting some strange error in the console output, namely:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "/Users/blah/Library/Application Support/Sublime Text 3/Packages/JSHint Gutter/JSHint.py", line 54, in run
    hint_point = self.view.text_point(int(line_no) - 1, int(column_no) - 1)
ValueError: invalid literal for int() with base 10: 'NaN'
```

Here are some screenshots of sublime as proof:

Code (no error shown on gutter):
![screen shot 2016-02-23 at 21 06 38](https://cloud.githubusercontent.com/assets/1199451/13263448/4586320a-da72-11e5-805a-140997204345.png)

Output from my grunt linter:
![screen shot 2016-02-23 at 21 07 02](https://cloud.githubusercontent.com/assets/1199451/13263439/3fd85b08-da72-11e5-83ea-7f7ccef505ab.png)

Any ideas on if this is a bug or a configuration issue?

**Comment by victorporof** [comment]
Doesn't look like the jshint options are incorrect. I bet `ValueError: invalid literal for int() with base 10: 'NaN'` is the actual error. I unfortunately can't reproduce this locally though :(

**Comment by byterider** [comment]
I have the same error, and when I insert the following, the error goes away:
// jshint camelcase: false

**Comment by byterider** [comment]
This fix works for me (in ~/Library/Application Support/Sublime Text 3/Packages/JSHint Gutter/JSHint.py, line 54):
`      hint_point = self.view.text_point(int(line_no) - 1, int(column_no if column_no != "NaN" else "1") - 1)
`
