### ISSUE TITLE
How to solve "require is not defined" and "console is not defined" ?

### ISSUE THREAD

**Issue by JimishF** [victorporof/Sublime-JSHint#131]
![image](https://cloud.githubusercontent.com/assets/8057628/14120662/67f80f56-f611-11e5-8de9-4a57e296dd93.png)

**Comment by JimishF** [comment]
I found a solution for it like write 
`/* jshint node: true */`
but How to do this globally ?

**Comment by victorporof** [comment]
readme https://github.com/victorporof/Sublime-JSHint#using-your-own-jshintrc-options

**Comment by JimishF** [comment]
Thank you! Solved it :)

**Comment by basil2style** [comment]
Thank you very much

**Comment by yangyili** [comment]
add config  {"node": true} in .jshint file

**Comment by thaodhbk0406** [comment]
Thank you so much!

**Comment by elirehema** [comment]
@JimishF add this in your .jshintrc 
![image](https://user-images.githubusercontent.com/29277048/85676632-74a9ec00-b6cf-11ea-8abd-811edb269a86.png)

**Comment by educationaldesk** [comment]
Thank you for giving the solution.
