### ISSUE TITLE
incompatible values for the 'undefined' and 'undefined' linting options.

### ISSUE THREAD

**Issue by zymr-keshav** [victorporof/Sublime-JSHint#142]
- OS: macOS Sierra **10.12.5** .
- Sublime Text: Build **3126** .
- jshint **v2.9.5** .
- eslint **v4.4.0** 

In my angular project , I am using IIFE in all .js files as below

```
(function() {
  'use strict';
  angular.module().controller(function () { //....code.... });
})();
```

using this Jshint always gives the error

> incompatible values for the 'undefined' and 'undefined' linting options.

I have .jshintrc file in my root directory with below rules

```
{
    "browser": true,
    "esnext": true,
    "node": true,
    "esversion": 6,
    "globals" : {
        "moment": true,
        "angular": true,
        "saveAs": true
    }
}
```

Please suggest me How to fix this issue?

Also mentioned the problem on [SO](https://stackoverflow.com/questions/45540611/sublime-text3-jshint-error-incompatible-values-for-undefined-and-undefined) :

**Comment by victorporof** [comment]
Thanks for filing. Can you please also post the output from sublime’s console?

**Comment by zymr-keshav** [comment]
Thanks for response, I have  checked the sublime-console using _control+ `_, it gives below data repeatedly

```
Using node.js path on 'osx': /usr/local/bin/node
Using JSHint globals: {"angular":true,"moment":true,"saveAs":true}
Using JSHint options: {
  "browser": true,
  "esnext": true,
  "strict": "global",
  "undef": true,
  "unused": true,
  "node": true,
  "immed": true,
  "esversion": 6
}

SublimeLinter: jshint output:
/opt/baffle-ui/WebUI/src/app/controllers/application.controller.js: line 0, col 0, Incompatible values for the 'esversion' and 'esnext' linting options. 
```



additionally, I have found that this plugin gives the error even file start from comments (/** or //); here I am attaching the screenshot for the better clarification.


![erro_undefined](https://user-images.githubusercontent.com/20237647/29025783-199e8e32-7b96-11e7-8589-cc28e074df46.png)

**Comment by zymr-keshav** [comment]
ah! I found the cause while replying this. as there is mixing of 2 _.jshintrc_ files. one is default ( which can be viewed by (right click from a file in ST3 > JSHint > Set Liniting Preferences ) and other is in my  project root directory and also there are 2 property `esnext` and `esversion` written which I think is not valid, [refrence](https://github.com/victorporof/Sublime-JSHint/issues/126 )


so first clear all comments from  1st _.jshintrc_ (**/Users/<usernam>/Library/Application Support/Sublime Text 3/Packages/JSHint Gutter/.jshintrc**)  and remove `esversion` property from my root _.jshintrc_ file and everything is working fine now.
