### ISSUE TITLE
Sublime-JSHint not using .jshintrc in Sublime Text build 3062

### ISSUE THREAD

**Issue by supernintendo** [victorporof/Sublime-JSHint#75]
Hello. It appears that Sublime-JSHint is not finding my .jshintrc after upgrading to Sublime Text build 3062. I am getting `'module' is not defined` as well as many other warnings that should be resolved by the .jshintrc in the root directory of my project. This issue does not occur in Sublime builds 3061 and below. Thanks.

**Comment by aldendaniels** [comment]
I'm still having this issue - build 3065

**Comment by IanCaunce** [comment]
Same. It used to work for me, but for some reason it now doesn't. Maybe a recent update broke things?
